CREATE TABLE habits (
	id INTEGER PRIMARY KEY,
	name TEXT CHECK(LENGTH(name) <= 128) NOT NULL, 
	type TEXT CHECK(type IN ("BINARY", "DURATION", "AMOUNT")) NOT NULL default "BINARY",
	target INTEGER NOT NULL DEFAULT 1,
	is_positive INTEGER NOT NULL DEFAULT 1,
	is_archived INTEGER NOT NULL DEFAULT 0,
	creation_timestamp TEXT NOT NULL default CURRENT_TIMESTAMP
);

CREATE TABLE habit_entries (
	id INTEGER PRIMARY KEY,
	data INTEGER,
	creation_timestamp TEXT NOT NULL DEFAULT timestamp,
	habit_id INTEGER NOT NULL,
	FOREIGN KEY(habit_id) REFERENCES habits(id) ON DELETE CASCADE
);
