// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Habit } from "./Habit";
import type { HabitEntry } from "./HabitEntry";

export interface HabitWithEntries { habit: Habit, entries: Array<HabitEntry>, }