// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface HabitEntry { id: bigint, habit_id: bigint, value: number | null, completion_date: string, creation_timestamp: string, }