// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HabitType } from "./HabitType";

export interface HabitValues { name: string, habit_type: HabitType, target: number, is_positive: boolean, is_archived: boolean, }